# Generated by Django 3.1.3 on 2021-06-14 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='APORTADOR',
        ),
    ]
