# Generated by Django 3.2.3 on 2021-06-15 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_aporte'),
    ]

    operations = [
        migrations.DeleteModel(
            name='APORTE',
        ),
    ]
