# Generated by Django 3.2.3 on 2021-07-07 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_residente'),
    ]

    operations = [
        migrations.DeleteModel(
            name='residente',
        ),
    ]
