# Generated by Django 3.2.3 on 2021-07-07 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_delete_residente'),
    ]

    operations = [
        migrations.CreateModel(
            name='residente',
            fields=[
                ('rutResident', models.IntegerField(primary_key=True, serialize=False, verbose_name='Rut aporte')),
                ('nombsResident', models.CharField(max_length=50, verbose_name='Nombre residente')),
                ('edadResident', models.IntegerField(verbose_name='Edad residente')),
                ('tutorResi', models.CharField(max_length=50, verbose_name='Nombre tutor')),
                ('medicaResident', models.CharField(max_length=50, verbose_name='Medicamentos')),
                ('saludResident', models.CharField(max_length=50, verbose_name='salud del residente')),
                ('cuidadResident', models.CharField(max_length=50, verbose_name='Cuidados especiales')),
                ('fichaResidente', models.ImageField(null=True, upload_to='Ficha_medica')),
            ],
        ),
    ]
