# Generated by Django 3.2.3 on 2021-07-07 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_residente'),
    ]

    operations = [
        migrations.CreateModel(
            name='ingresos',
            fields=[
                ('idIngreso', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id registro de salida')),
                ('salidaRes', models.CharField(max_length=15, verbose_name='Salida de residente')),
                ('ingresoRes', models.CharField(max_length=15, verbose_name='Ingreso de residente')),
                ('Residente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.residente')),
            ],
        ),
    ]
